url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

title:
exclude: ["_assets", "gulp", ".gitignore", "gulpfile.js", "package.json", "README.md", "node_modules"]
keep_files: ["assets"]
